[settings]
activate_aggressive = true               # mise shims win over other PATH entries

[tools]
atuin = { version = "latest", os = ["linux"] }
ripgrep = { version = "latest", os = ["linux"] }
eza = { version = "latest", os = ["linux"] }
zoxide = { version = "latest", os = ["linux"] }
jq = { version = "latest", os = ["linux"] }
yq = { version = "latest", os = ["linux"] }
github-cli = { version = "latest", os = ["linux"] }
kubectx = { version = "latest", os = ["macos"] }
kubens = { version = "latest", os = ["macos"] }
usage = 'latest'
go = 'latest'
golangci-lint = 'latest'
node = "24.13.1"
"npm:ccstatusline" = 'latest'
