[[ssh-keys]]
item = "id_ed25519_github"
vault = "Dotfiles"

# Add my Git signing key from my Work vault
[[ssh-keys]]
item = "Git Signing Key"
vault = "work"

[[ssh-keys]]
item = "Hetzner"
vault = "Personal"

[[ssh-keys]]
item = "openclaw"
vault = "OpenClaw"
